from app.models.auth import AdminUser
from app.models.competition import (
    Competition,
    CompetitionTeam,
    Group,
    GroupTeam,
    Stage,
)
from app.models.content import Ad, AppVersion, News, Venue
from app.models.core import AgeGroup, Club, Coach, Player, Season
from app.models.match import (
    Match,
    MatchCard,
    MatchGoal,
    MatchPenaltyShootout,
    MatchPlayer,
    MatchSubstitution,
)
from app.models.team import ClubStaff, PlayerTeam, Team, TeamCoach
from app.models.tla3bny import (
    Tla3bnyAd,
    Tla3bnyAdSettings,
    Tla3bnyAuditLog,
    Tla3bnyAcademy,
    Tla3bnyAcademyBranch,
    Tla3bnyAcademyManager,
    Tla3bnyAgeCategory,
    Tla3bnyCoach,
    Tla3bnyCompetition,
    Tla3bnyCompetitionAdmin,
    Tla3bnyCompetitionAge,
    Tla3bnyCompetitionPlayer,
    Tla3bnyCompetitionTeam,
    Tla3bnyGroup,
    Tla3bnyGroupTeam,
    Tla3bnyLineup,
    Tla3bnyLineupSlot,
    Tla3bnyMatch,
    Tla3bnyMatchEvent,
    Tla3bnyNews,
    Tla3bnyPlayer,
    Tla3bnyPlayerFile,
    Tla3bnyPlayerTeam,
    Tla3bnySeason,
    Tla3bnyStage,
    Tla3bnyTeam,
    Tla3bnyUser,
)

__all__ = [
    # core
    "Club",
    "Season",
    "AgeGroup",
    "Player",
    "Coach",
    # team
    "Team",
    "TeamCoach",
    "PlayerTeam",
    "ClubStaff",
    # competition
    "Competition",
    "CompetitionTeam",
    "Stage",
    "Group",
    "GroupTeam",
    # match
    "Match",
    "MatchPlayer",
    "MatchGoal",
    "MatchCard",
    "MatchSubstitution",
    "MatchPenaltyShootout",
    # content
    "Venue",
    "News",
    "Ad",
    "AppVersion",
    # auth
    "AdminUser",
    # tla3bny (youth-academy competitions subdomain)
    "Tla3bnyAd",
    "Tla3bnyAdSettings",
    "Tla3bnyAuditLog",
    "Tla3bnyUser",
    "Tla3bnyAcademy",
    "Tla3bnyAcademyBranch",
    "Tla3bnyAcademyManager",
    "Tla3bnyAgeCategory",
    "Tla3bnyTeam",
    "Tla3bnyCoach",
    "Tla3bnyPlayer",
    "Tla3bnyPlayerFile",
    "Tla3bnyPlayerTeam",
    "Tla3bnySeason",
    "Tla3bnyCompetition",
    "Tla3bnyCompetitionAdmin",
    "Tla3bnyCompetitionAge",
    "Tla3bnyCompetitionTeam",
    "Tla3bnyCompetitionPlayer",
    "Tla3bnyStage",
    "Tla3bnyGroup",
    "Tla3bnyGroupTeam",
    "Tla3bnyMatch",
    "Tla3bnyMatchEvent",
    "Tla3bnyLineup",
    "Tla3bnyLineupSlot",
    "Tla3bnyNews",
]
